{
  "uid" : "c0b54bd6b7962174",
  "name" : "test__EnergyValue__usage_1",
  "fullName" : "src.sw.allotmentclub.tests.test_electricity#test__EnergyValue__usage_1",
  "historyId" : "054d78db251fb74e40d832a7c98f4051",
  "time" : {
    "start" : 1616578908984,
    "stop" : 1616578908984,
    "duration" : 0
  },
  "description" : "Usage is 0 if value is None.",
  "descriptionHtml" : "<p>Usage is 0 if value is None.</p>\n",
  "status" : "broken",
  "statusMessage" : "psycopg2.OperationalError: FATAL:  password authentication failed for user \"allotmentclubtest\"\nFATAL:  password authentication failed for user \"allotmentclubtest\"",
  "statusTrace" : "Traceback (most recent call last):\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/conftest.py\", line 244, in database_session\n    request, 'sw_allotmentclub_', ENGINE_NAME\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/conftest.py\", line 211, in database_fixture_factory\n    db.create()\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/conftest.py\", line 149, in create\n    port=self.port,\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/psycopg2/__init__.py\", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: FATAL:  password authentication failed for user \"allotmentclubtest\"\nFATAL:  password authentication failed for user \"allotmentclubtest\"",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "database_session",
    "time" : {
      "start" : 1616578908801,
      "stop" : 1616578908820,
      "duration" : 19
    },
    "status" : "broken",
    "statusMessage" : "psycopg2.OperationalError: FATAL:  password authentication failed for user \"allotmentclubtest\"\nFATAL:  password authentication failed for user \"allotmentclubtest\"\n\n",
    "statusTrace" : "  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/_pytest/fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/_pytest/fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/conftest.py\", line 244, in database_session\n    request, 'sw_allotmentclub_', ENGINE_NAME\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/conftest.py\", line 211, in database_fixture_factory\n    db.create()\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/conftest.py\", line 149, in create\n    port=self.port,\n  File \"/home/sweh/actions-runner/_work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/psycopg2/__init__.py\", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "src.sw.allotmentclub.tests"
  }, {
    "name" : "suite",
    "value" : "test_electricity"
  }, {
    "name" : "host",
    "value" : "hawking"
  }, {
    "name" : "thread",
    "value" : "1205485-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "src.sw.allotmentclub.tests.test_electricity"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "c0b54bd6b7962174.json",
  "parameterValues" : [ ]
}