{
  "uid" : "6702efc382dede3c",
  "name" : "test_MapDownloadView__call__1",
  "fullName" : "src.sw.allotmentclub.browser.tests.test_map#test_MapDownloadView__call__1",
  "historyId" : "96820bb4df734d299af40822f42ae1cc",
  "time" : {
    "start" : 1610717185652,
    "stop" : 1610717186868,
    "duration" : 1216
  },
  "description" : "Map can be downloaded.",
  "descriptionHtml" : "<p>Map can be downloaded.</p>\n",
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'pdftotext': 'pdftotext'",
  "statusTrace" : "Traceback (most recent call last):\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/browser/tests/test_map.py\", line 34, in test_MapDownloadView__call__1\n    assertFileEqual(browser.contents, 'test_map_print.pdf')\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/conftest.py\", line 85, in assertFileEqual\n    changes = compute_changes(master_file, generated_file)\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pdf_diff/command_line.py\", line 14, in compute_changes\n    docs = [serialize_pdf(0, pdf_fn_1, top_margin, bottom_margin), serialize_pdf(1, pdf_fn_2, top_margin, bottom_margin)]\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pdf_diff/command_line.py\", line 29, in serialize_pdf\n    for run in box_generator:\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pdf_diff/command_line.py\", line 99, in mark_eol_hyphens\n    for next_box in boxes:\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pdf_diff/command_line.py\", line 61, in pdf_to_bboxes\n    xml = subprocess.check_output([\"pdftotext\", \"-bbox\", fn, \"/dev/stdout\"])\n  File \"/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/subprocess.py\", line 356, in check_output\n    **kwargs).stdout\n  File \"/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/subprocess.py\", line 423, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File \"/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/subprocess.py\", line 729, in __init__\n    restore_signals, start_new_session)\n  File \"/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/subprocess.py\", line 1364, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\nFileNotFoundError: [Errno 2] No such file or directory: 'pdftotext': 'pdftotext'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "verwalter",
    "time" : {
      "start" : 1610717185370,
      "stop" : 1610717185644,
      "duration" : 274
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "organization",
    "time" : {
      "start" : 1610717185366,
      "stop" : 1610717185370,
      "duration" : 4
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "wsgi_app",
    "time" : {
      "start" : 1610717163803,
      "stop" : 1610717165737,
      "duration" : 1934
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "database_session",
    "time" : {
      "start" : 1610717163108,
      "stop" : 1610717163803,
      "duration" : 695
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "portal_app",
    "time" : {
      "start" : 1610717163803,
      "stop" : 1610717163803,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "browser",
    "time" : {
      "start" : 1610717185645,
      "stop" : 1610717185645,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "database",
    "time" : {
      "start" : 1610717185272,
      "stop" : 1610717185366,
      "duration" : 94
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "json_fixture",
    "time" : {
      "start" : 1610717185645,
      "stop" : 1610717185651,
      "duration" : 6
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "Map can be downloaded.",
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'pdftotext': 'pdftotext'",
    "statusTrace" : "Traceback (most recent call last):\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/browser/tests/test_map.py\", line 34, in test_MapDownloadView__call__1\n    assertFileEqual(browser.contents, 'test_map_print.pdf')\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/src/sw/allotmentclub/conftest.py\", line 85, in assertFileEqual\n    changes = compute_changes(master_file, generated_file)\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pdf_diff/command_line.py\", line 14, in compute_changes\n    docs = [serialize_pdf(0, pdf_fn_1, top_margin, bottom_margin), serialize_pdf(1, pdf_fn_2, top_margin, bottom_margin)]\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pdf_diff/command_line.py\", line 29, in serialize_pdf\n    for run in box_generator:\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pdf_diff/command_line.py\", line 99, in mark_eol_hyphens\n    for next_box in boxes:\n  File \"/home/runner/work/sw.allotmentclub.backend/sw.allotmentclub.backend/.pytest/unclean/lib/python3.6/site-packages/pdf_diff/command_line.py\", line 61, in pdf_to_bboxes\n    xml = subprocess.check_output([\"pdftotext\", \"-bbox\", fn, \"/dev/stdout\"])\n  File \"/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/subprocess.py\", line 356, in check_output\n    **kwargs).stdout\n  File \"/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/subprocess.py\", line 423, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File \"/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/subprocess.py\", line 729, in __init__\n    restore_signals, start_new_session)\n  File \"/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/subprocess.py\", line 1364, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\nFileNotFoundError: [Errno 2] No such file or directory: 'pdftotext': 'pdftotext'",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "3ae6c577f2506195",
      "name" : "log",
      "source" : "3ae6c577f2506195.txt",
      "type" : "text/plain",
      "size" : 81
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "database_session::1",
    "time" : {
      "start" : 1610717201282,
      "stop" : 1610717201283,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "database_session::dropdb",
    "time" : {
      "start" : 1610717201283,
      "stop" : 1610717201416,
      "duration" : 133
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "database::0",
    "time" : {
      "start" : 1610717186874,
      "stop" : 1610717186875,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "src.sw.allotmentclub.browser.tests"
  }, {
    "name" : "suite",
    "value" : "test_map"
  }, {
    "name" : "host",
    "value" : "fv-az176-222"
  }, {
    "name" : "thread",
    "value" : "4932-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "src.sw.allotmentclub.browser.tests.test_map"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 2,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 2
      },
      "items" : [ {
        "uid" : "4f0f16f3bf709a9",
        "reportUrl" : "https://sweh.github.io/sw.allotmentclub.backend/2//#testresult/4f0f16f3bf709a9",
        "status" : "broken",
        "statusDetails" : "psycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?",
        "time" : {
          "start" : 1610715010586,
          "stop" : 1610715010586,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "6702efc382dede3c.json",
  "parameterValues" : [ ]
}